import {
  KamisatoAyakaImage,
  KamisatoAyatoImage,
  YaeMikoImage,
  AlbedoImage,
  AmberImage,
  AratakiIttoImage,
  BarbaraImage,
  BeidouImage,
  BennettImage,
  ChongyunImage,
  DilucImage,
  DionaImage,
  EulaImage,
  FischlImage,
  GanyuImage,
  GorouImage,
  HuTaoImage,
  JeanImage,
  KaedeharaKazuhaImage,
  KaeyaImage,
  KeqingImage,
  KleeImage,
  KujouSaraImage,
  LisaImage,
  MonaImage,
  NingguangImage,
  NoelleImage,
  QiqiImage,
  RaidenShogunImage,
  RazorImage,
  RosariaImage,
  SangonomiyaKokomiImage,
  SayuImage,
  ShenheImage,
  SucroseImage,
  TartagliaImage,
  ThomaImage,
  VentiImage,
  XianglingImage,
  XiaoImage,
  XingqiuImage,
  XinyanImage,
  YanfeiImage,
  YoimiyaImage,
  YunJinImage,
  ZhongliImage,
  YelanImage,
  HeizouImage,
  LumineImage,
  AetherImage
} from '../assets/banner_characters'

import {
  AlbedoBackground,
  KamisatoAyakaBackground,
  YelanBackground,
  YaeMikoBackground,
  BennettBackground,
  ShikanoinHeizouBackground,
  BarbaraBackground,
  ShenheBackground,
  YoimiyaBackground,
  KaedeharaKazuhaBackground,
  GanyuBackground,
  HuTaoBackground,
  XiaoBackground,
  MonaBackground,
  RaidenShogunBackground,
  EulaBackground,
  DionaBackground,
  DilucBackground,
  FischlBackground,
  GorouBackground,
  AmberBackground,
  JeanBackground,
  KaeyaBackground,
  KamisatoAyatoBackground,
  BeidouBackground,
  AratakiIttoBackground,
  KeqingBackground,
  KleeBackground,
  KujouSaraBackground,
  LisaBackground,
  NingguangBackground,
  NoelleBackground,
  QiqiBackground,
  RazorBackground,
  RosariaBackground,
  SangonomiyaKokomiBackground,
  SayuBackground,
  SucroseBackground,
  TartagliaBackground,
  ChongyunBackground,
  ThomaBackground,
  VentiBackground,
  XianglingBackground,
  XingqiuBackground,
  XinyanBackground,
  YanfeiBackground,
  YunJinBackground,
  ZhongliBackground,
  AetherBackground,
  LumineBackground
} from '../assets/background_characters'

const CharactersGenshin = [
  {
    id: 0,
    name: 'Kamisato Ayaka',
    gender: 'Feminino',
    constellation: 'Grus Nivis',
    vision: 'Cryo',
    weapon: 'Espada',
    birthday: '28/09',
    stars: 5,
    region: 'Inazuma',
    color: '#2cbcc9',
    image: KamisatoAyakaImage,
    bgImage: KamisatoAyakaBackground
  },
  {
    id: 1,
    name: 'Yelan',
    gender: 'Feminino',
    constellation: 'Umbrabilis Orchis',
    vision: 'Hydro',
    weapon: 'Arco',
    birthday: '20/04',
    stars: 5,
    region: 'Liyue',
    color: '#0071E9',
    image: YelanImage,
    bgImage: YelanBackground
  },
  {
    id: 2,
    name: 'Yae Miko',
    gender: 'Feminino',
    constellation: 'Divina Vulpes',
    vision: 'Electro',
    weapon: 'Catalisador',
    birthday: '27/06',
    stars: 5,
    region: 'Inazuma',
    color: '#9B1BD1',
    image: YaeMikoImage,
    bgImage: YaeMikoBackground
  },
  {
    id: 3,
    name: 'Shikanoin Heizou',
    gender: 'Masculino',
    constellation: '',
    vision: 'Anemo',
    weapon: 'Catalisador',
    birthday: 'None',
    stars: 5,
    region: 'Inazuma',
    color: '#20C9A7',
    image: HeizouImage,
    bgImage: ShikanoinHeizouBackground
  },
  {
    id: 4,
    name: 'Shenhe',
    gender: 'Feminino',
    constellation: 'Crista Doloris',
    vision: 'Cryo',
    weapon: 'Lança',
    birthday: '10/03',
    stars: 5,
    region: 'Liyue',
    color: '#2cbcc9',
    image: ShenheImage,
    bgImage: ShenheBackground
  },
  {
    id: 5,
    name: 'Yoimiya',
    gender: 'Feminino',
    constellation: 'Carassius Auratus',
    vision: 'Pyro',
    weapon: 'Arco',
    birthday: '21/06',
    stars: 5,
    region: 'Inazuma',
    color: '#EE1E1E',
    image: YoimiyaImage,
    bgImage: YoimiyaBackground
  },
  {
    id: 6,
    name: 'Kaedehara Kazuha',
    gender: 'Masculino',
    constellation: 'Acer Palmatum',
    vision: 'Anemo',
    weapon: 'Espada',
    birthday: '29/10',
    stars: 5,
    region: 'Inazuma',
    color: '#20C9A7',
    image: KaedeharaKazuhaImage,
    bgImage: KaedeharaKazuhaBackground
  },
  {
    id: 7,
    name: 'Ganyu',
    gender: 'Feminino',
    constellation: 'Sinae Unicornis',
    vision: 'Cryo',
    weapon: 'Arco',
    birthday: '02/12',
    stars: 5,
    region: 'Liyue',
    color: '#2cbcc9',
    image: GanyuImage,
    bgImage: GanyuBackground
  },
  {
    id: 8,
    name: 'Hu Tao',
    gender: 'Feminino',
    constellation: 'Papilio Charontis',
    vision: 'Pyro',
    weapon: 'Lança',
    birthday: '15/07',
    stars: 5,
    region: 'Liyue',
    color: '#EE1E1E',
    image: HuTaoImage,
    bgImage: HuTaoBackground
  },
  {
    id: 9,
    name: 'Xiao',
    gender: 'Masculino',
    constellation: 'Alatus Nemeseos',
    vision: 'Anemo',
    weapon: 'Lança',
    birthday: '17/04',
    stars: 5,
    region: 'Liyue',
    color: '#20C9A7',
    image: XiaoImage,
    bgImage: XiaoBackground
  },
  {
    id: 10,
    name: 'Mona',
    gender: 'Feminino',
    constellation: 'Astrolabos',
    vision: 'Hydro',
    weapon: 'Catalisador',
    birthday: '31/08',
    stars: 5,
    region: 'Mondstadt',
    color: '#0071E9',
    image: MonaImage,
    bgImage: MonaBackground
  },
  {
    id: 11,
    name: 'Raiden Ei',
    gender: 'Feminino',
    constellation: 'Imperatrix Umbrosa',
    vision: 'Electro',
    weapon: 'Lança',
    birthday: '26/06',
    stars: 5,
    region: 'Inazuma',
    color: '#9B1BD1',
    image: RaidenShogunImage,
    bgImage: RaidenShogunBackground
  },
  {
    id: 12,
    name: 'Eula',
    gender: 'Feminino',
    constellation: 'Aphros Delos',
    vision: 'Cryo',
    weapon: 'Espadão',
    birthday: '25/10',
    stars: 5,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: EulaImage,
    bgImage: EulaBackground
  },
  {
    id: 13,
    name: 'Diona',
    gender: 'Feminino',
    constellation: 'Feles',
    vision: 'Cryo',
    weapon: 'Arco',
    birthday: '18/01',
    stars: 4,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: DionaImage,
    bgImage: DionaBackground
  },
  {
    id: 14,
    name: 'Keqing',
    gender: 'Feminino',
    constellation: 'Trulla Cementarii',
    vision: 'Electro',
    weapon: 'Espada',
    birthday: '20/11',
    stars: 5,
    region: 'Liyue',
    color: '#9B1BD1',
    image: KeqingImage,
    bgImage: KeqingBackground
  },
  {
    id: 15,
    name: 'Tartaglia',
    gender: 'Masculino',
    constellation: 'Monoceros Caeli',
    vision: 'Hydro',
    weapon: 'Arco',
    birthday: '20/07',
    stars: 5,
    region: 'Snezhnaya',
    color: '#0071E9',
    image: TartagliaImage,
    bgImage: TartagliaBackground
  },
  {
    id: 16,
    name: 'Bennett',
    gender: 'Masculino',
    constellation: 'Rota Calamitas',
    vision: 'Pyro',
    weapon: 'Espada',
    birthday: '29/02',
    stars: 4,
    region: 'Mondstadt',
    color: '#EE1E1E',
    image: BennettImage,
    bgImage: BennettBackground
  },
  {
    id: 17,
    name: 'Jean',
    gender: 'Feminino',
    constellation: 'Leo Minor',
    vision: 'Anemo',
    weapon: 'Espada',
    birthday: '14/03',
    stars: 5,
    region: 'Mondstadt',
    color: '#20C9A7',
    image: JeanImage,
    bgImage: JeanBackground
  },
  {
    id: 18,
    name: 'Barbara',
    gender: 'Feminino',
    constellation: 'Crater',
    vision: 'Hydro',
    weapon: 'Catalisador',
    birthday: '05/07',
    stars: 4,
    region: 'Mondstadt',
    color: '#0071E9',
    image: BarbaraImage,
    bgImage: BarbaraBackground
  },
  {
    id: 19,
    name: 'Kaeya',
    gender: 'Masculino',
    constellation: 'Pavo Ocellus',
    vision: 'Cryo',
    weapon: 'Espada',
    birthday: '30/11',
    stars: 4,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: KaeyaImage,
    bgImage: KaeyaBackground
  },
  {
    id: 20,
    name: 'Chongyun',
    gender: 'Masculino',
    constellation: 'Nubis Caesor',
    vision: 'Cryo',
    weapon: 'Espadão',
    birthday: '07/09',
    stars: 4,
    region: 'Liyue',
    color: '#2cbcc9',
    image: ChongyunImage,
    bgImage: ChongyunBackground
  },
  {
    id: 21,
    name: 'Klee',
    gender: 'Feminino',
    constellation: 'Trifolium',
    vision: 'Pyro',
    weapon: 'Catalisador',
    birthday: '27/07',
    stars: 5,
    region: 'Mondstad',
    color: '#EE1E1E',
    image: KleeImage,
    bgImage: KleeBackground
  },
  {
    id: 22,
    name: 'Kujou Sara',
    gender: 'Feminino',
    constellation: 'Flabellum',
    vision: 'Electro',
    weapon: 'Arco',
    birthday: '14/07',
    stars: 4,
    region: 'Inazuma',
    color: '#9B1BD1',
    image: KujouSaraImage,
    bgImage: KujouSaraBackground
  },
  {
    id: 23,
    name: 'Lisa',
    gender: 'Feminino',
    constellation: 'Tempus Fugit',
    vision: 'Electro',
    weapon: 'Catalisador',
    birthday: '09/06',
    stars: 4,
    region: 'Mondstadt',
    color: '#9B1BD1',
    image: LisaImage,
    bgImage: LisaBackground
  },
  {
    id: 24,
    name: 'Diluc',
    gender: 'Masculino',
    constellation: 'Noctua',
    vision: 'Pyro',
    weapon: 'Espadão',
    birthday: '30/04',
    stars: 5,
    region: 'Mondstadt',
    color: '#EE1E1E',
    image: DilucImage,
    bgImage: DilucBackground
  },
  {
    id: 25,
    name: 'Ningguang',
    gender: 'Feminino',
    constellation: 'Opus Aequilibrium',
    vision: 'Geo',
    weapon: 'Catalisador',
    birthday: '26/08',
    stars: 4,
    region: 'Liyue',
    color: '#FFB400',
    image: NingguangImage,
    bgImage: NingguangBackground
  },
  {
    id: 26,
    name: 'Noelle',
    gender: 'Feminino',
    constellation: 'Parma Cordis',
    vision: 'Geo',
    weapon: 'Espadão',
    birthday: '21/03',
    stars: 4,
    region: 'Mondstadt',
    color: '#FFB400',
    image: NoelleImage,
    bgImage: NoelleBackground
  },
  {
    id: 27,
    name: 'Qiqi',
    gender: 'Feminino',
    constellation: 'Pristina Nola',
    vision: 'Cryo',
    weapon: 'Espada',
    birthday: '03/03',
    stars: 5,
    region: 'Liyue',
    color: '#2cbcc9',
    image: QiqiImage,
    bgImage: QiqiBackground
  },
  {
    id: 28,
    name: 'Fischl',
    gender: 'Feminino',
    constellation: 'Corvus',
    vision: 'Electro',
    weapon: 'Arco',
    birthday: '27/05',
    stars: 4,
    region: 'Mondstadt',
    color: '#9B1BD1',
    image: FischlImage,
    bgImage: FischlBackground
  },
  {
    id: 29,
    name: 'Razor',
    gender: 'Masculino',
    constellation: 'Lupus Minor',
    vision: 'Electro',
    weapon: 'Espadão',
    birthday: '09/09',
    stars: 4,
    region: 'Mondstadt',
    color: '#9B1BD1',
    image: RazorImage,
    bgImage: RazorBackground
  },
  {
    id: 30,
    name: 'Rosaria',
    gender: 'Feminino',
    constellation: 'Spinea Corona',
    vision: 'Cryo',
    weapon: 'Lança',
    birthday: '24/01',
    stars: 4,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: RosariaImage,
    bgImage: RosariaBackground
  },
  {
    id: 31,
    name: 'Sangonomiya Kokomi',
    gender: 'Feminino',
    constellation: 'Dracaena Somnolenta',
    vision: 'Hydro',
    weapon: 'Catalisador',
    birthday: '22/02',
    stars: 5,
    region: 'Inazuma',
    color: '#0071E9',
    image: SangonomiyaKokomiImage,
    bgImage: SangonomiyaKokomiBackground
  },
  {
    id: 32,
    name: 'Sayu',
    gender: 'Feminino',
    constellation: 'Nyctereutes Minor',
    vision: 'Anemo',
    weapon: 'Espadão',
    birthday: '19/10',
    stars: 4,
    region: 'Inazuma',
    color: '#20C9A7',
    image: SayuImage,
    bgImage: SayuBackground
  },
  {
    id: 33,
    name: 'Amber',
    gender: 'Feminino',
    constellation: 'Lepus',
    vision: 'Pyro',
    weapon: 'Arco',
    birthday: '10/08',
    stars: 4,
    region: 'Mondstadt',
    color: '#EE1E1E',
    image: AmberImage,
    bgImage: AmberBackground
  },
  {
    id: 34,
    name: 'Sucrose',
    gender: 'Feminino',
    constellation: 'Ampulla',
    vision: 'Anemo',
    weapon: 'Catalisador',
    birthday: '26/11',
    stars: 4,
    region: 'Mondstadt',
    color: '#20C9A7',
    image: SucroseImage,
    bgImage: SucroseBackground
  },
  {
    id: 35,
    name: 'Gorou',
    gender: 'Masculino',
    constellation: 'Canis Bellatoris',
    vision: 'Geo',
    weapon: 'Arco',
    birthday: '18/05',
    stars: 4,
    region: 'Inazuma',
    color: '#FFB400',
    image: GorouImage,
    bgImage: GorouBackground
  },
  {
    id: 36,
    name: 'Thoma',
    gender: 'Masculino',
    constellation: 'Rubeum Scutum',
    vision: 'Pyro',
    weapon: 'Lança',
    birthday: '09/01',
    stars: 4,
    region: 'Inazuma',
    color: '#EE1E1E',
    image: ThomaImage,
    bgImage: ThomaBackground
  },
  {
    id: 37,
    name: 'Venti',
    gender: 'Masculino',
    constellation: 'Carmen Dei',
    vision: 'Anemo',
    weapon: 'Arco',
    birthday: '16/06',
    stars: 5,
    region: 'Mondstadt',
    color: '#20C9A7',
    image: VentiImage,
    bgImage: VentiBackground
  },
  {
    id: 38,
    name: 'Xiangling',
    gender: 'Feminino',
    constellation: 'Trulla',
    vision: 'Pyro',
    weapon: 'Lança',
    birthday: '02/11',
    stars: 4,
    region: 'Liyue',
    color: '#EE1E1E',
    image: XianglingImage,
    bgImage: XianglingBackground
  },
  {
    id: 39,
    name: 'Beidou',
    gender: 'Feminino',
    constellation: 'Victor Mare',
    vision: 'Electro',
    weapon: 'Espadão',
    birthday: '14/02',
    stars: 4,
    region: 'Liyue',
    color: '#9B1BD1',
    image: BeidouImage,
    bgImage: BeidouBackground
  },
  {
    id: 40,
    name: 'Xingqiu',
    gender: 'Masculino',
    constellation: 'Fabulae Textile',
    vision: 'Hydro',
    weapon: 'Espada',
    birthday: '09/10',
    stars: 4,
    region: 'Liyue',
    color: '#0071E9',
    image: XingqiuImage,
    bgImage: XingqiuBackground
  },
  {
    id: 41,
    name: 'Yun Jin',
    gender: 'Feminino',
    constellation: 'Opera Grandis',
    vision: 'Geo',
    weapon: 'Lança',
    birthday: '21/05',
    stars: 4,
    region: 'Liyue',
    color: '#FFB400',
    image: YunJinImage,
    bgImage: YunJinBackground
  },
  {
    id: 42,
    name: 'Yanfei',
    gender: 'Feminino',
    constellation: 'Bestia Iustitia',
    vision: 'Pyro',
    weapon: 'Catalisador',
    birthday: '28/07',
    stars: 4,
    region: 'Liyue',
    color: '#EE1E1E',
    image: YanfeiImage,
    bgImage: YanfeiBackground
  },
  {
    id: 43,
    name: 'Arataki Itto',
    gender: 'Masculino',
    constellation: 'Taurus Iracundus',
    vision: 'Geo',
    weapon: 'Espadão',
    birthday: '01/06',
    stars: 5,
    region: 'Inazuma',
    color: '#FFB400',
    image: AratakiIttoImage,
    bgImage: AratakiIttoBackground
  },
  {
    id: 44,
    name: 'Xinyan',
    gender: 'Feminino',
    constellation: 'Fila Ignium',
    vision: 'Pyro',
    weapon: 'Espadão',
    birthday: '16/10',
    stars: 4,
    region: 'Liyue',
    color: '#EE1E1E',
    image: XinyanImage,
    bgImage: XinyanBackground
  },
  {
    id: 45,
    name: 'Zhongli',
    gender: 'Masculino',
    constellation: 'Lapis Dei',
    vision: 'Geo',
    weapon: 'Lança',
    birthday: '31/12',
    stars: 5,
    region: 'Liyue',
    color: '#FFB400',
    image: ZhongliImage,
    bgImage: ZhongliBackground
  },
  {
    id: 46,
    name: 'Kamisato Ayato',
    gender: 'Masculino',
    constellation: 'Cypressus Custos',
    vision: 'Hydro',
    weapon: 'Espada',
    birthday: '26/03',
    stars: 5,
    region: 'Inazuma',
    color: '#0071E9',
    image: KamisatoAyatoImage,
    bgImage: KamisatoAyatoBackground
  },
  {
    id: 47,
    name: 'Albedo',
    gender: 'Masculino',
    constellation: 'Princeps Cretaceus',
    vision: 'Geo',
    weapon: 'Espada',
    birthday: '13/09',
    stars: 5,
    region: 'Mondstadt',
    color: '#FFB400',
    image: AlbedoImage,
    bgImage: AlbedoBackground
  },
  {
    id: 48,
    name: 'Aether',
    gender: 'Masculino',
    constellation: '',
    vision: '',
    weapon: 'Espada',
    birthday: '',
    stars: 5,
    region: '',
    color: '#000000',
    image: AetherImage,
    bgImage: AetherBackground
  },
  {
    id: 49,
    name: 'Lumine',
    gender: 'Feminino',
    constellation: '',
    vision: '',
    weapon: 'Espada',
    birthday: '',
    stars: 5,
    region: '',
    color: '#000000',
    image: LumineImage,
    bgImage: LumineBackground
  }
]

export default CharactersGenshin
