import {
  KamisatoAyakaImage,
  KamisatoAyatoImage,
  YaeMikoImage,
  AlbedoImage,
  AmberImage,
  AratakiIttoImage,
  BarbaraImage,
  BeidouImage,
  BennettImage,
  ChongyunImage,
  DilucImage,
  DionaImage,
  EulaImage,
  FischlImage,
  GanyuImage,
  GorouImage,
  HuTaoImage,
  JeanImage,
  KaedeharaKazuhaImage,
  KaeyaImage,
  KeqingImage,
  KleeImage,
  KujouSaraImage,
  LisaImage,
  MonaImage,
  NigguangImage,
  NoelleImage,
  QiqiImage,
  RaidenShogunImage,
  RazorImage,
  RosariaImage,
  SangonomiyaKokomiImage,
  SayuImage,
  ShenheImage,
  SucroseImage,
  TartagliaImage,
  ThomaImage,
  VentiImage,
  XianglingImage,
  XiaoImage,
  XingqiuImage,
  XinyanImage,
  YanfeiImage,
  YoimiyaImage,
  YunJinImage,
  ZhongliImage,
  YelanImage,
  TravelerImage
} from '../assets/index'

const CharactersGenshin = [
  {
    id: 0,
    name: 'Kamisato Ayaka',
    vision: 'Cryo',
    weapon: 'Sword',
    birthday: '28/09',
    stars: 5,
    region: 'Inazuma',
    color: '#2cbcc9',
    image: KamisatoAyakaImage
  },
  {
    id: 1,
    name: 'Yelan',
    vision: 'Hydro',
    weapon: 'Bow',
    birthday: '',
    stars: 5,
    region: 'Liyue',
    color: '#0071E9',
    image: YelanImage
  },
  {
    id: 2,
    name: 'Yae Miko',
    vision: 'Electro',
    weapon: 'Catalyst',
    birthday: '27/06',
    stars: 5,
    region: 'Inazuma',
    color: '#9B1BD1',
    image: YaeMikoImage
  },
  {
    id: 3,
    name: 'Albedo',
    vision: 'Geo',
    weapon: 'Sword',
    birthday: '',
    stars: 5,
    region: 'Mondstadt',
    color: '#FFB400',
    image: AlbedoImage
  },
  {
    id: 4,
    name: 'Amber',
    vision: 'Pyro',
    weapon: 'Bow',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#EE1E1E',
    image: AmberImage
  },
  {
    id: 5,
    name: 'Arataki Itto',
    vision: 'Geo',
    weapon: 'Claymore',
    birthday: '',
    stars: 5,
    region: 'Inazuma',
    color: '#FFB400',
    image: AratakiIttoImage
  },
  {
    id: 6,
    name: 'Barbara',
    vision: 'Hydro',
    weapon: 'Catalyst',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#0071E9',
    image: BarbaraImage
  },
  {
    id: 7,
    name: 'Beidou',
    vision: 'Electro',
    weapon: 'Claymore',
    birthday: '',
    stars: 4,
    region: 'Liyue',
    color: '#9B1BD1',
    image: BeidouImage
  },
  {
    id: 8,
    name: 'Bennett',
    vision: 'Pyro',
    weapon: 'Sword',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#EE1E1E',
    image: BennettImage
  },
  {
    id: 9,
    name: 'Chongyun',
    vision: 'Cryo',
    weapon: 'Claymore',
    birthday: '',
    stars: 4,
    region: 'Liyue',
    color: '#2cbcc9',
    image: ChongyunImage
  },
  {
    id: 10,
    name: 'Diluc',
    vision: 'Pyro',
    weapon: 'Claymore',
    birthday: '',
    stars: 5,
    region: 'Mondstadt',
    color: '#EE1E1E',
    image: DilucImage
  },
  {
    id: 11,
    name: 'Diona',
    vision: 'Cryo',
    weapon: 'Bow',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: DionaImage
  },
  {
    id: 12,
    name: 'Eula',
    vision: 'Cryo',
    weapon: 'Claymore',
    birthday: '',
    stars: 5,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: EulaImage
  },
  {
    id: 13,
    name: 'Fischl',
    vision: 'Electro',
    weapon: 'Bow',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#9B1BD1',
    image: FischlImage
  },
  {
    id: 14,
    name: 'Ganyu',
    vision: 'Cryo',
    weapon: 'Bow',
    birthday: '',
    stars: 5,
    region: 'Liyue',
    color: '#2cbcc9',
    image: GanyuImage
  },
  {
    id: 15,
    name: 'Gorou',
    vision: 'Geo',
    weapon: 'Bow',
    birthday: '',
    stars: 4,
    region: 'Inazuma',
    color: '#FFB400',
    image: GorouImage
  },
  {
    id: 16,
    name: 'Hu Tao',
    vision: 'Pyro',
    weapon: 'Polearm',
    birthday: '',
    stars: 5,
    region: 'Liyue',
    color: '#EE1E1E',
    image: HuTaoImage
  },
  {
    id: 17,
    name: 'Jean',
    vision: 'Anemo',
    weapon: 'Sword',
    birthday: '',
    stars: 5,
    region: 'Mondstadt',
    color: '#20C9A7',
    image: JeanImage
  },
  {
    id: 18,
    name: 'Kaedehara Kazuha',
    vision: 'Anemo',
    weapon: 'Sword',
    birthday: '',
    stars: 5,
    region: 'Inazuma',
    color: '#20C9A7',
    image: KaedeharaKazuhaImage
  },
  {
    id: 19,
    name: 'Kaeya',
    vision: 'Cryo',
    weapon: 'Sword',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: KaeyaImage
  },
  {
    id: 20,
    name: 'Keqing',
    vision: 'Electro',
    weapon: 'Sword',
    birthday: '',
    stars: 5,
    region: 'Liyue',
    color: '#9B1BD1',
    image: KeqingImage
  },
  {
    id: 21,
    name: 'Klee',
    vision: 'Pyro',
    weapon: 'Catalyst',
    birthday: '',
    stars: 5,
    region: 'Mondstad',
    color: '#EE1E1E',
    image: KleeImage
  },
  {
    id: 22,
    name: 'Kujou Sara',
    vision: 'Electro',
    weapon: 'Bow',
    birthday: '',
    stars: 4,
    region: 'Inazuma',
    color: '#9B1BD1',
    image: KujouSaraImage
  },
  {
    id: 23,
    name: 'Lisa',
    vision: 'Electro',
    weapon: 'Catalyst',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#9B1BD1',
    image: LisaImage
  },
  {
    id: 24,
    name: 'Mona',
    vision: 'Hydro',
    weapon: 'Catalyst',
    birthday: '',
    stars: 5,
    region: 'Mondstadt',
    color: '#0071E9',
    image: MonaImage
  },
  {
    id: 25,
    name: 'Nigguang',
    vision: 'Geo',
    weapon: 'Catalyst',
    birthday: '',
    stars: 4,
    region: 'Liyue',
    color: '#FFB400',
    image: NigguangImage
  },
  {
    id: 26,
    name: 'Noelle',
    vision: 'Geo',
    weapon: 'Claymore',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#FFB400',
    image: NoelleImage
  },
  {
    id: 27,
    name: 'Qiqi',
    vision: 'Cryo',
    weapon: 'Sword',
    birthday: '',
    stars: 5,
    region: 'Liyue',
    color: '#2cbcc9',
    image: QiqiImage
  },
  {
    id: 28,
    name: 'Raiden Shogun',
    vision: 'Electro',
    weapon: 'Polearm',
    birthday: '',
    stars: 5,
    region: 'Inazuma',
    color: '#9B1BD1',
    image: RaidenShogunImage
  },
  {
    id: 29,
    name: 'Razor',
    vision: 'Electro',
    weapon: 'Claymore',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#9B1BD1',
    image: RazorImage
  },
  {
    id: 30,
    name: 'Rosaria',
    vision: 'Cryo',
    weapon: 'Polearm',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: RosariaImage
  },
  {
    id: 31,
    name: 'Sangonomiya Kokomi',
    vision: 'Hydro',
    weapon: 'Catalyst',
    birthday: '',
    stars: 5,
    region: 'Inazuma',
    color: '#0071E9',
    image: SangonomiyaKokomiImage
  },
  {
    id: 32,
    name: 'Sayu',
    vision: 'Anemo',
    weapon: 'Claymore',
    birthday: '',
    stars: 4,
    region: 'Inazuma',
    color: '#20C9A7',
    image: SayuImage
  },
  {
    id: 33,
    name: 'Shenhe',
    vision: 'Cryo',
    weapon: 'Polearm',
    birthday: '',
    stars: 5,
    region: 'Liyue',
    color: '#2cbcc9',
    image: ShenheImage
  },
  {
    id: 34,
    name: 'Sucrose',
    vision: 'Anemo',
    weapon: 'Catalyst',
    birthday: '',
    stars: 4,
    region: 'Mondstadt',
    color: '#20C9A7',
    image: SucroseImage
  },
  {
    id: 35,
    name: 'Tartaglia',
    vision: 'Hydro',
    weapon: 'Bow',
    birthday: '',
    stars: 5,
    region: 'Snezhnaya',
    color: '#0071E9',
    image: TartagliaImage
  },
  {
    id: 36,
    name: 'Thoma',
    vision: 'Pyro',
    weapon: 'Polearm',
    birthday: '',
    stars: 4,
    region: 'Inazuma',
    color: '#EE1E1E',
    image: ThomaImage
  },
  {
    id: 37,
    name: 'Venti',
    vision: 'Anemo',
    weapon: 'bow',
    birthday: '',
    stars: 5,
    region: 'Mondstadt',
    color: '#20C9A7',
    image: VentiImage
  },
  {
    id: 38,
    name: 'Xiangling',
    vision: 'Pyro',
    weapon: 'Polearm',
    birthday: '',
    stars: 4,
    region: 'Liyue',
    color: '#EE1E1E',
    image: XianglingImage
  },
  {
    id: 39,
    name: 'Xiao',
    vision: 'Anemo',
    weapon: 'Polearm',
    birthday: '',
    stars: 5,
    region: 'Liyue',
    color: '#20C9A7',
    image: XiaoImage
  },
  {
    id: 40,
    name: 'Xingqiu',
    vision: 'Hydro',
    weapon: 'Sword',
    birthday: '',
    stars: 4,
    region: 'Liyue',
    color: '#0071E9',
    image: XingqiuImage
  },
  {
    id: 41,
    name: 'Xinyan',
    vision: 'Pyro',
    weapon: 'Claymore',
    birthday: '',
    stars: 4,
    region: 'Liyue',
    color: '#EE1E1E',
    image: XinyanImage
  },
  {
    id: 42,
    name: 'Yanfei',
    vision: 'Pyro',
    weapon: 'Catalyst',
    birthday: '',
    stars: 4,
    region: 'Liyue',
    color: '#EE1E1E',
    image: YanfeiImage
  },
  {
    id: 43,
    name: 'Yoimiya',
    vision: 'Pyro',
    weapon: 'Bow',
    birthday: '',
    stars: 5,
    region: 'Inazuma',
    color: '#EE1E1E',
    image: YoimiyaImage
  },
  {
    id: 44,
    name: 'Yun Jin',
    vision: 'Geo',
    weapon: 'Polearm',
    birthday: '',
    stars: 4,
    region: 'Liyue',
    color: '#FFB400',
    image: YunJinImage
  },
  {
    id: 45,
    name: 'Zhongli',
    vision: 'Geo',
    weapon: 'Polearm',
    birthday: '',
    stars: 5,
    region: 'Liyue',
    color: '#FFB400',
    image: ZhongliImage
  },
  {
    id: 46,
    name: 'Kamisato Ayato',
    vision: 'Hydro',
    weapon: 'Sword',
    birthday: '26/03',
    stars: 5,
    region: 'Inazuma',
    color: '#0071E9',
    image: KamisatoAyatoImage
  },
  {
    id: 47,
    name: 'Traveler',
    vision: 'None',
    weapon: 'Sword',
    birthday: 'None',
    stars: 5,
    region: 'None',
    color: 'black',
    image: TravelerImage
  }
]

export default CharactersGenshin
