import {
  KamisatoAyakaImage,
  KamisatoAyatoImage,
  YaeMikoImage,
  AlbedoImage,
  AmberImage,
  AratakiIttoImage,
  BarbaraImage,
  BeidouImage,
  BennettImage,
  ChongyunImage,
  DilucImage,
  DionaImage,
  EulaImage,
  FischlImage,
  GanyuImage,
  GorouImage,
  HuTaoImage,
  JeanImage,
  KaedeharaKazuhaImage,
  KaeyaImage,
  KeqingImage,
  KleeImage,
  KujouSaraImage,
  LisaImage,
  MonaImage,
  NingguangImage,
  NoelleImage,
  QiqiImage,
  RaidenShogunImage,
  RazorImage,
  RosariaImage,
  SangonomiyaKokomiImage,
  SayuImage,
  ShenheImage,
  SucroseImage,
  TartagliaImage,
  ThomaImage,
  VentiImage,
  XianglingImage,
  XiaoImage,
  XingqiuImage,
  XinyanImage,
  YanfeiImage,
  YoimiyaImage,
  YunJinImage,
  ZhongliImage,
  YelanImage,
  HeizouImage,
  TravelerImage
} from '../assets/index'

const CharactersGenshin = [
  {
    id: 0,
    name: 'Kamisato Ayaka',
    vision: 'Cryo',
    weapon: 'Espada',
    birthday: '28/09',
    stars: 5,
    region: 'Inazuma',
    color: '#2cbcc9',
    image: KamisatoAyakaImage
  },
  {
    id: 1,
    name: 'Yelan',
    vision: 'Hydro',
    weapon: 'Arco',
    birthday: '',
    stars: 5,
    region: 'Liyue',
    color: '#0071E9',
    image: YelanImage
  },
  {
    id: 2,
    name: 'Yae Miko',
    vision: 'Electro',
    weapon: 'Catalisador',
    birthday: '27/06',
    stars: 5,
    region: 'Inazuma',
    color: '#9B1BD1',
    image: YaeMikoImage
  },
  {
    id: 3,
    name: 'Heizou',
    vision: 'Anemo',
    weapon: 'Catalisador',
    birthday: 'None',
    stars: 5,
    region: 'Inazuma',
    color: '#20C9A7',
    image: HeizouImage
  },
  {
    id: 4,
    name: 'Shenhe',
    vision: 'Cryo',
    weapon: 'Lança',
    birthday: '10/03',
    stars: 5,
    region: 'Liyue',
    color: '#2cbcc9',
    image: ShenheImage
  },
  {
    id: 5,
    name: 'Yoimiya',
    vision: 'Pyro',
    weapon: 'Arco',
    birthday: '21/06',
    stars: 5,
    region: 'Inazuma',
    color: '#EE1E1E',
    image: YoimiyaImage
  },
  {
    id: 6,
    name: 'Kaedehara Kazuha',
    vision: 'Anemo',
    weapon: 'Espada',
    birthday: '29/10',
    stars: 5,
    region: 'Inazuma',
    color: '#20C9A7',
    image: KaedeharaKazuhaImage
  },
  {
    id: 7,
    name: 'Ganyu',
    vision: 'Cryo',
    weapon: 'Arco',
    birthday: '02/12',
    stars: 5,
    region: 'Liyue',
    color: '#2cbcc9',
    image: GanyuImage
  },
  {
    id: 8,
    name: 'Hu Tao',
    vision: 'Pyro',
    weapon: 'Lança',
    birthday: '15/07',
    stars: 5,
    region: 'Liyue',
    color: '#EE1E1E',
    image: HuTaoImage
  },
  {
    id: 9,
    name: 'Xiao',
    vision: 'Anemo',
    weapon: 'Lança',
    birthday: '17/04',
    stars: 5,
    region: 'Liyue',
    color: '#20C9A7',
    image: XiaoImage
  },
  {
    id: 10,
    name: 'Mona',
    vision: 'Hydro',
    weapon: 'Catalisador',
    birthday: '31/08',
    stars: 5,
    region: 'Mondstadt',
    color: '#0071E9',
    image: MonaImage
  },
  {
    id: 11,
    name: 'Raiden Shogun',
    vision: 'Electro',
    weapon: 'Lança',
    birthday: '26/06',
    stars: 5,
    region: 'Inazuma',
    color: '#9B1BD1',
    image: RaidenShogunImage
  },
  {
    id: 12,
    name: 'Eula',
    vision: 'Cryo',
    weapon: 'Espadão',
    birthday: '25/10',
    stars: 5,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: EulaImage
  },
  {
    id: 13,
    name: 'Diona',
    vision: 'Cryo',
    weapon: 'Arco',
    birthday: '18/01',
    stars: 4,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: DionaImage
  },
  {
    id: 14,
    name: 'Keqing - Rainha',
    vision: 'Electro',
    weapon: 'Espada',
    birthday: '20/11',
    stars: 5,
    region: 'Liyue',
    color: '#9B1BD1',
    image: KeqingImage
  },
  {
    id: 15,
    name: 'Tartaglia',
    vision: 'Hydro',
    weapon: 'Arco',
    birthday: '20/07',
    stars: 5,
    region: 'Snezhnaya',
    color: '#0071E9',
    image: TartagliaImage
  },
  {
    id: 16,
    name: 'Bennett',
    vision: 'Pyro',
    weapon: 'Espada',
    birthday: '29/02',
    stars: 4,
    region: 'Mondstadt',
    color: '#EE1E1E',
    image: BennettImage
  },
  {
    id: 17,
    name: 'Jean',
    vision: 'Anemo',
    weapon: 'Espada',
    birthday: '14/03',
    stars: 5,
    region: 'Mondstadt',
    color: '#20C9A7',
    image: JeanImage
  },
  {
    id: 18,
    name: 'Barbara',
    vision: 'Hydro',
    weapon: 'Catalisador',
    birthday: '05/07',
    stars: 4,
    region: 'Mondstadt',
    color: '#0071E9',
    image: BarbaraImage
  },
  {
    id: 19,
    name: 'Kaeya',
    vision: 'Cryo',
    weapon: 'Espada',
    birthday: '30/11',
    stars: 4,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: KaeyaImage
  },
  {
    id: 20,
    name: 'Chongyun',
    vision: 'Cryo',
    weapon: 'Espadão',
    birthday: '07/09',
    stars: 4,
    region: 'Liyue',
    color: '#2cbcc9',
    image: ChongyunImage
  },
  {
    id: 21,
    name: 'Klee',
    vision: 'Pyro',
    weapon: 'Catalisador',
    birthday: '27/07',
    stars: 5,
    region: 'Mondstad',
    color: '#EE1E1E',
    image: KleeImage
  },
  {
    id: 22,
    name: 'Kujou Sara',
    vision: 'Electro',
    weapon: 'Arco',
    birthday: '14/07',
    stars: 4,
    region: 'Inazuma',
    color: '#9B1BD1',
    image: KujouSaraImage
  },
  {
    id: 23,
    name: 'Lisa',
    vision: 'Electro',
    weapon: 'Catalisador',
    birthday: '09/06',
    stars: 4,
    region: 'Mondstadt',
    color: '#9B1BD1',
    image: LisaImage
  },
  {
    id: 24,
    name: 'Diluc',
    vision: 'Pyro',
    weapon: 'Espadão',
    birthday: '30/04',
    stars: 5,
    region: 'Mondstadt',
    color: '#EE1E1E',
    image: DilucImage
  },
  {
    id: 25,
    name: 'Ningguang',
    vision: 'Geo',
    weapon: 'Catalisador',
    birthday: '26/08',
    stars: 4,
    region: 'Liyue',
    color: '#FFB400',
    image: NingguangImage
  },
  {
    id: 26,
    name: 'Noelle',
    vision: 'Geo',
    weapon: 'Espadão',
    birthday: '21/03',
    stars: 4,
    region: 'Mondstadt',
    color: '#FFB400',
    image: NoelleImage
  },
  {
    id: 27,
    name: 'Qiqi',
    vision: 'Cryo',
    weapon: 'Espada',
    birthday: '03/03',
    stars: 5,
    region: 'Liyue',
    color: '#2cbcc9',
    image: QiqiImage
  },
  {
    id: 28,
    name: 'Fischl',
    vision: 'Electro',
    weapon: 'Arco',
    birthday: '27/05',
    stars: 4,
    region: 'Mondstadt',
    color: '#9B1BD1',
    image: FischlImage
  },
  {
    id: 29,
    name: 'Razor',
    vision: 'Electro',
    weapon: 'Espadão',
    birthday: '09/09',
    stars: 4,
    region: 'Mondstadt',
    color: '#9B1BD1',
    image: RazorImage
  },
  {
    id: 30,
    name: 'Rosaria',
    vision: 'Cryo',
    weapon: 'Lança',
    birthday: '24/01',
    stars: 4,
    region: 'Mondstadt',
    color: '#2cbcc9',
    image: RosariaImage
  },
  {
    id: 31,
    name: 'Sangonomiya Kokomi',
    vision: 'Hydro',
    weapon: 'Catalisador',
    birthday: '22/02',
    stars: 5,
    region: 'Inazuma',
    color: '#0071E9',
    image: SangonomiyaKokomiImage
  },
  {
    id: 32,
    name: 'Sayu',
    vision: 'Anemo',
    weapon: 'Espadão',
    birthday: '19/10',
    stars: 4,
    region: 'Inazuma',
    color: '#20C9A7',
    image: SayuImage
  },
  {
    id: 33,
    name: 'Amber',
    vision: 'Pyro',
    weapon: 'Arco',
    birthday: '10/08',
    stars: 4,
    region: 'Mondstadt',
    color: '#EE1E1E',
    image: AmberImage
  },
  {
    id: 34,
    name: 'Sucrose',
    vision: 'Anemo',
    weapon: 'Catalisador',
    birthday: '26/11',
    stars: 4,
    region: 'Mondstadt',
    color: '#20C9A7',
    image: SucroseImage
  },
  {
    id: 35,
    name: 'Gorou',
    vision: 'Geo',
    weapon: 'Arco',
    birthday: '18/05',
    stars: 4,
    region: 'Inazuma',
    color: '#FFB400',
    image: GorouImage
  },
  {
    id: 36,
    name: 'Thoma',
    vision: 'Pyro',
    weapon: 'Lança',
    birthday: '09/01',
    stars: 4,
    region: 'Inazuma',
    color: '#EE1E1E',
    image: ThomaImage
  },
  {
    id: 37,
    name: 'Venti',
    vision: 'Anemo',
    weapon: 'Arco',
    birthday: '16/06',
    stars: 5,
    region: 'Mondstadt',
    color: '#20C9A7',
    image: VentiImage
  },
  {
    id: 38,
    name: 'Xiangling',
    vision: 'Pyro',
    weapon: 'Lança',
    birthday: '02/11',
    stars: 4,
    region: 'Liyue',
    color: '#EE1E1E',
    image: XianglingImage
  },
  {
    id: 39,
    name: 'Beidou',
    vision: 'Electro',
    weapon: 'Espadão',
    birthday: '14/02',
    stars: 4,
    region: 'Liyue',
    color: '#9B1BD1',
    image: BeidouImage
  },
  {
    id: 40,
    name: 'Xingqiu',
    vision: 'Hydro',
    weapon: 'Espada',
    birthday: '09/10',
    stars: 4,
    region: 'Liyue',
    color: '#0071E9',
    image: XingqiuImage
  },
  {
    id: 41,
    name: 'Yun Jin',
    vision: 'Geo',
    weapon: 'Lança',
    birthday: '21/05',
    stars: 4,
    region: 'Liyue',
    color: '#FFB400',
    image: YunJinImage
  },
  {
    id: 42,
    name: 'Yanfei',
    vision: 'Pyro',
    weapon: 'Catalisador',
    birthday: '28/07',
    stars: 4,
    region: 'Liyue',
    color: '#EE1E1E',
    image: YanfeiImage
  },
  {
    id: 43,
    name: 'Arataki Itto',
    vision: 'Geo',
    weapon: 'Espadão',
    birthday: '01/06',
    stars: 5,
    region: 'Inazuma',
    color: '#FFB400',
    image: AratakiIttoImage
  },
  {
    id: 44,
    name: 'Xinyan',
    vision: 'Pyro',
    weapon: 'Espadão',
    birthday: '16/10',
    stars: 4,
    region: 'Liyue',
    color: '#EE1E1E',
    image: XinyanImage
  },
  {
    id: 45,
    name: 'Zhongli',
    vision: 'Geo',
    weapon: 'Lança',
    birthday: '31/12',
    stars: 5,
    region: 'Liyue',
    color: '#FFB400',
    image: ZhongliImage
  },
  {
    id: 46,
    name: 'Kamisato Ayato',
    vision: 'Hydro',
    weapon: 'Espada',
    birthday: '26/03',
    stars: 5,
    region: 'Inazuma',
    color: '#0071E9',
    image: KamisatoAyatoImage
  },
  {
    id: 3,
    name: 'Albedo',
    vision: 'Geo',
    weapon: 'Espada',
    birthday: '13/09',
    stars: 5,
    region: 'Mondstadt',
    color: '#FFB400',
    image: AlbedoImage
  },
  {
    id: 47,
    name: 'Traveler',
    vision: 'None',
    weapon: 'Espada',
    birthday: 'None',
    stars: 5,
    region: 'None',
    color: 'black',
    image: TravelerImage
  }
]

export default CharactersGenshin
